apiVersion: v1
kind: Secret
metadata:
  name: coinwave-secrets
type: Opaque
stringData:
  mysql-root-password: rootpassword
  mysql-database: coinwave
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coinwave-config
data:
  GIN_MODE: release
  DB_DSN_TEMPLATE: "root:rootpassword@tcp(mysql:3306)/coinwave?charset=utf8mb4&parseTime=True&loc=Local"
  REDIS_ADDR: "redis:6379"
