apiVersion: v1
kind: Secret
metadata:
  name: coinwave-secrets
type: Opaque
stringData:
  mysql-root-password: rootpassword
  mysql-database: coinwave
  volc-auth-token: "97443eb3-4d60-4738-bf9d-e7bf364566d2"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coinwave-config
data:
  GIN_MODE: release
  DB_DSN_TEMPLATE: "root:rootpassword@tcp(mysql:3306)/coinwave?charset=utf8mb4&parseTime=True&loc=Local"
  REDIS_ADDR: "redis:6379"
  MILVUS_ADDRESS: "milvus:19530"
  VOLC_MODEL_EMBEDDING: "ep-20260119190844-zzrq7" # Replace with your Endpoint ID (e.g. ep-2024...)
  VOLC_MODEL_LLM: "ep-20260119190028-tmjkb"       # Replace with your Endpoint ID
